/*
 * Event.java
 *
 * Author: Jeff Blagg
 * Class: CS-360 - Mobile Architecture and Programming
 * Professor: Jerome DiMarzio
 * Date: October 2025
 */

package com.jeffblagg.eventtracker.entities;

import androidx.annotation.NonNull;
import androidx.room.Entity;
import androidx.room.ForeignKey;
import androidx.room.Index;
import androidx.room.PrimaryKey;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;

/**
 * Represents and defines the data model for a user's scheduled event.
 *
 * <p>Each event is stored in the Room database and linked to a specific user.
 * Events must include a title and event time, and may optionally include a description
 * and a color for the event card.</p>
 */
@Entity(
        tableName = "events",
        foreignKeys = @ForeignKey(
                entity = User.class,
                parentColumns = "id",
                childColumns = "userId",
                onDelete = ForeignKey.CASCADE),
        indices = @Index("userId")
)
public class Event {
   /**
    * Autogenerated id for the event.
    */
   @PrimaryKey(autoGenerate = true)
   public long id;

   /**
    * The id of the user associated with the event.
    */
   public String userId;

   /**
    * The time of the event, stored in milliseconds.
    */
   public long eventTime;

   /**
    * The title or name for the event. Cannot be {@code null}.
    */
   @NonNull
   public String title;

   /**
    * The description for the event.
    */
   public String description;

   /**
    * The color for the event's card background.
    */
   public Integer cardColor;

   /**
    * Constructor for an event object.
    *
    * @param userId The id of the associated user.
    * @param eventTime The time of the event, in milliseconds.
    * @param title The {@code NonNull} title of the event.
    * @param description The description of the event.
    * @param cardColor The background color for the event's card.
    */
   public Event(String userId, long eventTime,
                @NonNull String title, String description, Integer cardColor) {
      this.userId = userId;
      this.eventTime = eventTime;
      this.title = title;
      this.description = description;
      this.cardColor = cardColor;
   }
}
