/*
 * User.java
 *
 * Author: Jeff Blagg
 * Class: CS-360 - Mobile Architecture and Programming
 * Professor: Jerome DiMarzio
 * Date: October 2025
 */

package com.jeffblagg.eventtracker.entities;

import androidx.annotation.NonNull;
import androidx.room.Entity;
import androidx.room.Index;
import androidx.room.PrimaryKey;

/**
 * Represents and defines the data model for a user.
 *
 * <p>Each user is stored in the Room database. Users must include a
 * username and password.</p>
 */
@Entity(tableName = "users", indices = @Index(value = "username", unique = true))
public class User {
    /**
     * Autogenerated id for the user.
     */
    @PrimaryKey(autoGenerate = true)
    public long id;

    /**
     * The username for the user.
     */
    @NonNull
    public String username;

    /**
     * The password for the user.
     */
    @NonNull
    public String password;

    /**
     * Constructor for a user object.
     *
     * @param username The username for the user. {@code NonNull}
     * @param password The password for the user. {@code NonNull}
     */
    public User(@NonNull String username, @NonNull String password) {
        this.username = username;
        this.password = password;
    }
}
